タイトルを使ったEntryの特定をfile_pathから取得するように変更

diff --git a/.github/workflows/pull-draft.yaml b/.github/workflows/pull-draft.yaml
--- a/.github/workflows/pull-draft.yaml
+++ b/.github/workflows/pull-draft.yaml
@@ -24,8 +24,27 @@ jobs:
           fetch-depth: 0
       - name: setup
         uses: hatena/hatenablog-workflows/.github/actions/setup@v1
+      - name: pull
+        run: |
+          blogsync pull ${{ inputs.BLOG_DOMAIN }}
+      - name: set entry path
+        id: set-entry-path
+        run: |
+          files=($(git ls-files -o --exclude-standard))
+          for file in ${files[@]}; do
+            title=$(yq --front-matter=extract '.Title' "$file")
+            if [[ "$title" == ${{ inputs.title }} ]]; then
+              entry_path="$file"
+            fi
+          done
+          if [[ -z "$entry_path" ]]; then
+            echo "Error: No draft entry titled ${{ inputs.title }} was found"
+            exit 1
+          fi
+          echo "ENTRY_PATH=$entry_path" >> $GITHUB_OUTPUT
       - name: pull draft by title
         uses: hatena/hatenablog-workflows/.github/actions/pull-draft-by-title@v1
         with:
           title: ${{ inputs.title }}
           BLOG_DOMAIN: ${{ inputs.BLOG_DOMAIN }}
+          ENTRY_PATH: ${{ steps.set-entry-path.outputs.ENTRY_PATH }}
